### ISSUE TITLE
The xml content exceeded the buffer quota

### ISSUE THREAD

**Issue by dnaveen2012** [MscrmTools/DamSim.SolutionTransferTool#11]
I am getting the below error on using solution transfer tool:

**an error occurred: the size necessary to buffer the xml content exceeded the buffer quota**

Thanks

**Comment by MscrmTools** [comment]
What are the conditions of solution transfer?
What version of CRM source and target?
What size of solution archive?

**Comment by dnaveen2012** [comment]
I am connecting to the version of both (Version 1710 (9.0.2.1470) online).

I am just transferring the solutions form one instance to another. so getting the error.
the solution contains 350 web resources.

**Comment by MscrmTools** [comment]
Are you up to date with your XrmToolBox and plugin?

**Comment by dnaveen2012** [comment]
Yes, Today I downloaded this tool.
I just started using the plugin.

**Comment by MscrmTools** [comment]
Does it still happen? I never faced the situation and I'm using it quite heavily
