### ISSUE TITLE
Latest update Incompatible with CRM 2015

### ISSUE THREAD

**Issue by dodgster02** [MscrmTools/DamSim.SolutionTransferTool#12]
Using version 1.2018.9.6, it seems as though changes that work with D365 make this version no longer compatible with CRM 2015.

I currently get the following error when attempting to transfer a solution from my various CRM 2015 on premise environments

![image](https://user-images.githubusercontent.com/26326026/46528260-41845100-c88b-11e8-9def-67fed00ddf00.png)

**Comment by MscrmTools** [comment]
Can you try with this new version?
[DamSim.SolutionTransferTool.zip](https://github.com/MscrmTools/DamSim.SolutionTransferTool/files/2472380/DamSim.SolutionTransferTool.zip)

**Comment by dodgster02** [comment]
I've just tried importing another solution which previously failed using the new version in your zip file and it works perfectly.

The new layout is also much better :)

**Comment by MscrmTools** [comment]
Thank you!
I will release this new version soon.
Thank you for your feedback
