### ISSUE TITLE
Timeout during export after 2 min, no matter how high the timeout setting is

### ISSUE THREAD

**Issue by maeg02** [MscrmTools/DamSim.SolutionTransferTool#17]
Consider that you have an dynamics environment with some first party apps.
Then when you use this tool to transfer solutions you get a timeout after two minutes.

![2020-04-06 14_52_28-Eon Visa - Microsoft Visual Studio](https://user-images.githubusercontent.com/2965347/78829621-f51d5280-79e6-11ea-9e08-ec5c26beb83b.png)

and there is no download log file on import

![2020-04-06 14_56_28-Error](https://user-images.githubusercontent.com/2965347/78829643-036b6e80-79e7-11ea-9d5e-4164da63a51e.png)

**Comment by MscrmTools** [comment]
I will check this.
Thanks for reporting

**Comment by MscrmTools** [comment]
Ok, I should remove the timeout from the settings of this tool as it is not used.
The timeout has to be defined in the XrmToolBox connection itself
![image](https://user-images.githubusercontent.com/10774317/78868009-65a58d00-7a42-11ea-95c9-8891d93b7d84.png)

**Comment by maeg02** [comment]
Good info, I will make sure to change that one instead.
