### ISSUE TITLE
Solutions will not load

### ISSUE THREAD

**Issue by soliver99** [MscrmTools/DamSim.SolutionTransferTool#2]
I have a source environment and a target environment selected but when I click "Load Solutions" nothing happens.  When I click "Transfer Solution" it tells me I have to select a source and target environment (even though I have already selected both)
![solution transfer](https://cloud.githubusercontent.com/assets/17131583/16428322/2cbf28be-3d26-11e6-9c0e-82b39770305d.jpg)

**Comment by MscrmTools** [comment]
What is your screen resolution?? I even don't see the list of solutions... 
If you can't see the list of solution, then you can't transfer them

**Comment by soliver99** [comment]
I am an administrator so shouldn’t I be able to see the list of solutions?  I can see them in Settings/Customizations/Solutions

**Comment by MscrmTools** [comment]
My point is: on your screenshot, we can't see the solutions and we should.
It seems the resolution is too small to see the tool correctly

**Comment by soliver99** [comment]
Ha Ha!  That was the problem….just needed to maximize the window ☺
