### ISSUE TITLE
Feature request: solution version increment

### ISSUE THREAD

**Issue by amervitz** [MscrmTools/DamSim.SolutionTransferTool#21]
I'm loving this plugin, thanks for making it.

It would be really helpful if it could also increment the solution version as part of the export. An idea how this could be specified is to have one or more settings under the general settings which lets you choose what digit of the version to increment.

e.g. 
- Increment solution version (boolean): True, False
- Solution version increment strategy (dropdown): major (x.0.0.0), minor (0.x.0.0), build (0.0.x.0), revision (0.0.0.x).

**Comment by MscrmTools** [comment]
Great suggestion! I will try to work on it
