### ISSUE TITLE
Newer version not available in xrmtoolbox

### ISSUE THREAD

**Issue by Suxsem** [MscrmTools/DamSim.SolutionTransferTool#23]
Dear @MscrmTools ,
latest version of the tool has not been deployed to xrmtoolbox (https://www.xrmtoolbox.com/plugins/DamSim.SolutionTransferTool/).
Can you please check?

**Comment by MscrmTools** [comment]
Thank you for reporting.
I updated the tool. Just need to wait for the portal cache to refresh
