### ISSUE TITLE
Plugin doesn't work anymore since the 1.2021.4.18 update 

### ISSUE THREAD

**Issue by Gmanunta81GFPS** [MscrmTools/DamSim.SolutionTransferTool#24]
Hi,

I can export a solution
I cannot import it anymore 
I cannot publish it anymore 

I rolled back to the previous version(the 1.2021.3.16 version worked fine)

**Comment by MscrmTools** [comment]
When you say "I cannot import anymore" what is the behavior? error? never starts the import process?

**Comment by Gmanunta81GFPS** [comment]
these are the screenshot sequence
1.
![2021-05-19 18_23_18-](https://user-images.githubusercontent.com/78032433/118851002-9efd2d00-b8d1-11eb-919b-195e766c573d.png)
2.
![2021-05-19 18_23_45-](https://user-images.githubusercontent.com/78032433/118851017-a3c1e100-b8d1-11eb-81a2-1912c3e8d8c9.png)
3.
![2021-05-19 18_23_53-](https://user-images.githubusercontent.com/78032433/118851047-ab818580-b8d1-11eb-934f-0e1c65e6491d.png)
4.
![2021-05-19 18_37_56-](https://user-images.githubusercontent.com/78032433/118851072-b1776680-b8d1-11eb-8650-dde597b0d0cf.png)

**Comment by SteveTe** [comment]
I'm experiencing the same issues. Looks like the transfer solution button is calling the download solution code?

**Comment by MscrmTools** [comment]
Good catch! Issue found and fixed

**Comment by Gmanunta81GFPS** [comment]
Hi everyone 

I am sorry to get in delay with all of you

 I can confirm thank you very much
