### ISSUE TITLE
Importing solutions stuck at 0%

### ISSUE THREAD

**Issue by Reigningfear** [MscrmTools/DamSim.SolutionTransferTool#28]
Hello,

After updating to the latest version of the plugin, I am noticing that when exporting a solution from one environment to the other, the GUI will be stuck at 0%. However, it appear as though it is actually initiating and finishing the import process. In these cases, it looks like it continually trying to import because I am seeing numerous duplicate job errors in my environment. I have tried to uninstall the plugin and reinstall with the same result. It was progressing as expected prior to updating the plugin. 

Example of duplicate jobs:
![image](https://user-images.githubusercontent.com/1781212/126883202-05a5beb8-f402-4b9e-ac5b-105d71524eba.png)

**Comment by MscrmTools** [comment]
I have noticed the same but wasn't sure it was due to the tool itself or to the platform.
I will double check the code to find out what the issue is
Thank you for reporting

**Comment by MscrmTools** [comment]
@Reigningfear I'm not sure the problem really comes from the tool. It seems something was wrong on the platform. Anyway, I will update code to avoid multiple submission of the import request if the first import request got stuck
