### ISSUE TITLE
Solution Export Timeout

### ISSUE THREAD

**Issue by SteveTe** [MscrmTools/DamSim.SolutionTransferTool#30]
Hi There, 

Which timeout does solution Transfer Tool use when exporting a solution? It appears to default to 2 minutes and ignores the connection timeout.

I have notice that the first export of a medium solution takes CRM over 7 minutes spin up before actually exporting the solution. This causes the Solution Transfer Tool to timeout. You can re-run/retry the export, but end up doing this 3 times before it succeeds. 
Thereafter the exports happen within the 2 min and everything is ok.

Any chance that you can provide a way to configure a timeout or provide guidance on which timeout Solution Transfer Tool is using and how to change the setting?

Regards,

Steve

**Comment by MscrmTools** [comment]
The connection timeout is the one used for the solution export. If my connection timeout is 4 minutes, it will try to export for 4 minutes.
I know the first export can take a long time but this is an issue on Microsoft side. I'm in touch with the program manager to find a way to ease things here.

**Comment by SteveTe** [comment]
Thanks for your feedback and hopefully Microsoft fixes the delay.

I'm interested in which connection type you are using as I'm not seeing the ability to set the connection timeout (or honoured if in the config).

We use the Microsoft Login Control,

***@***.***

Which doesn't give you the option to specify a timeout.

***@***.***

***@***.***

***@***.***

I've set the values as follows in the XRMToolbox config file:

***@***.***

But these values appear to be ignored as the timeout still happens after 2 minutes.

Regards,

Steve

**Comment by MscrmTools** [comment]
I must admit I never use Microsoft Login Control for my connections. I'm using Wizard or Oauth ones

**Comment by SteveTe** [comment]
I switched back to wizard and re-created the connection with a timeout value, and it is honouring the timeout value.

Appreciate your help.

Steve
