### ISSUE TITLE
Solution ordering

### ISSUE THREAD

**Issue by bwmodular** [MscrmTools/DamSim.SolutionTransferTool#35]
Hi, 
I love this tool and it saves so much time - thanks!

The only issue I have is that the order in which solutions is displayed. Here's what I see when I open the tool:
![image](https://user-images.githubusercontent.com/1889586/195106114-8d42ea53-90fc-4ffb-b365-bfd2f86c3b91.png)
As you can see, the solutions are not ordered by any of the column headings. Maybe it's a date format issue as I see that there was an issue concerning this which was resolved a long time ago: https://github.com/MscrmTools/DamSim.SolutionTransferTool/pull/3 which is now resolved.

Secondly, and related to this, if I do then decide to order the solutions by date, most recent first (which would be my preferred default), I have to click the Installed On column 3 times to get the desired result, which is just odd.

Neither of these are showstoppers, just mentioning them if they are easy to fix.

Thanks again!

**Comment by MscrmTools** [comment]
Hi @bwmodular, thank you for the feedback. I will work on it

**Comment by MscrmTools** [comment]
Will be available soon in the next release
