### ISSUE TITLE
Toolbox won't update to the new version

### ISSUE THREAD

**Issue by bwmodular** [MscrmTools/DamSim.SolutionTransferTool#39]
Hi there,
the toolbox is reporting a new version of the Solution Transfer Tool, but when you update it, the toolbox restarts and still reports that there is an update to perform.
There was a similar issue with a different tool which was reported here:
https://github.com/MscrmTools/XrmToolBox/issues/1218
A mismatch between the assembly version number and the Nuget version number.
Hopefully not a biggy to fix.
Thanks,
Ben

**Comment by jsdanie1** [comment]
Yep also seeing this, glad somebody beat me to the ticket!

**Comment by MscrmTools** [comment]
known issue. I will fix it asap

Thanks for reporting anyway :)

**Comment by jsdanie1** [comment]
Was this fixed? It got closed out, but it still doing this...?

**Comment by MscrmTools** [comment]
It should not. I published a be version

**Comment by jsdanie1** [comment]
Okay never mind it stopped doing it now. Thanks :)
