### ISSUE TITLE
Error when saving solution

### ISSUE THREAD

**Issue by PandaCoderHa** [MscrmTools/DamSim.SolutionTransferTool#40]
When I select auto save, the following error message will be displayed：

![RzaRrfrePd](https://github.com/MscrmTools/DamSim.SolutionTransferTool/assets/7019978/42609ebc-4783-429d-a971-ea79d35d81da)

**Comment by MscrmTools** [comment]
Can you check if a path has been defined for auto save in settings?

**Comment by PandaCoderHa** [comment]
The path is correct, and other solutions have been saved successfully before this. After the error message appears, click the retry button to export again and it will be saved successfully. The solution with the error message only contains entities, so it takes a little longer to export, not sure if that's related.

**Comment by MscrmTools** [comment]
Would you be able to translate asian characters to english? So that I try to understand the error message?

**Comment by PandaCoderHa** [comment]
> Would you be able to translate asian characters to english? So that I try to understand the error message?

The value cannot be null.
Parameter name: bytes

**Comment by PandaCoderHa** [comment]
hi @MscrmTools,  I checked the export history and found that the ones that failed were the ones that took longer than 2 minutes to export. Auto save fails when exporting for more than 2 minutes?

**Comment by MscrmTools** [comment]
It depends... Did you activate asynchronous export in settings or not?

**Comment by PandaCoderHa** [comment]
Thanks, guys. I turned on the asynchronous export and there's no exception.
