### ISSUE TITLE
Enhancement possible to transfer solution async

### ISSUE THREAD

**Issue by daggen** [MscrmTools/DamSim.SolutionTransferTool#6]
First of, Great tool!

I'm having issues with a crm instance which have many logged in users and it is slow. Hence it would be great if you get the option to import solutions async, reference http://www.inogic.com/blog/2014/05/asynchronous-solution-import/.

Aslo some helptext to the options. What is "export selected solution as managed" vs "convert to managed solution"

**Comment by MscrmTools** [comment]
It can become complicated to handle if we need to import multiple solutions on multiple organizations as I need to wait for each solution to be imported to start importing next solution

I will think about it
