### ISSUE TITLE
Solution Transfer Tool error

### ISSUE THREAD

**Issue by ahmadfl2000** [MscrmTools/DamSim.SolutionTransferTool#8]
dear all

i did try this tool for the first time, and it did export and import the solution, but workflows are broken, all these WFs are broken on the steps related to "create Case"  or "update Case".
any help? please let me know if you need me to provide any logs?

thanks,

**Comment by MscrmTools** [comment]
What do you mean by "all these WFs are broken" ?

**Comment by ahmadfl2000** [comment]
I mean all the workflows are in Draft status and cant be reactivated.

Thanks.

**Comment by MscrmTools** [comment]
Cannot tell if this is related to the tool or not...

If you use lookup to actual record from one organization, they might not exist in the target organization with the same id. That would lead to this kind of behavior. But it is not related to the tool if you are in this situation.

**Comment by ahmadfl2000** [comment]
Thanks you, the but the target organization is brand new, and I am migrating configurations only, so what do you advise me to do ?

Regards.

**Comment by MscrmTools** [comment]
When transfering workflows that use explicit lookup data, these data should be transfered with same ID too. You cannot just transfer workflows and expect they work
